# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

platform :ios do
  desc "Submit a new build to TestFlight"
  lane :beta do
    app_identifier = "com.calintamas.foobar"

    api_environment = "staging"
    if ENV["IS_PRODUCTION"] == "true"
      api_environment = "production"
    end
    ENV["ENVFILE"]=".env.#{api_environment}"

    puts "API_HOST: #{ENV['API_HOST']}"
    puts "IS_PRODUCTION: #{ENV['IS_PRODUCTION']}"
    puts "ENVFILE: #{ENV['ENVFILE']}"

    increment_version_number(
      xcodeproj: './ios/FooBar.xcodeproj',
      bump_type: "patch",
      # bump_type: "minor",
      # bump_type: "major",
      # version_number: "1.0.0"
    )
    increment_build_number(
      xcodeproj: './ios/FooBar.xcodeproj',
      # build_number: '74'
    )

    gym(
      project: './ios/FooBar.xcodeproj',
      scheme: "FooBar.#{api_environment}"
    )

    pilot(
      app_identifier: app_identifier,
      email: "itunesconnect_email",
      first_name: "itunesconnect_first_name",
      last_name: "itunesconnect_last_name",
      ipa: "./FooBar.ipa",
      distribute_external: true,
      skip_submission: true,
      skip_waiting_for_build_processing: false
    )
    end
  end

platform :android do
  desc "Submit a new build to Google Play Console"
  lane :beta do
    app_identifier = "com.calintamas.foobar"

    api_environment = "staging"
    if ENV["IS_PRODUCTION"] == "true"
      api_environment = "production"
    end
    ENV["ENVFILE"]=".env.#{api_environment}"

    puts "API_HOST: #{ENV['API_HOST']}"
    puts "IS_PRODUCTION: #{ENV['IS_PRODUCTION']}"
    puts "ENVFILE: #{ENV['ENVFILE']}"

    gradle_file = "./android/app/build.gradle"
    android_set_version_name(
      version_name: "1.0.0",
      gradle_file: gradle_file
    )

    android_set_version_code(
      gradle_file: gradle_file
    )

    gradle(
      project_dir: './android',
      task: 'assemble',
      build_type: 'release'
    )

    supply(
      json_key: 'google_play_console_key',
      track: 'beta',
      apk: './android/app/build/outputs/apk/release/app-release.apk',
      package_name: app_identifier
    )
  end
end
